#################################################
# Base configuration
#################################################

centos7-rpm:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos:7

  stage: package
  script:
    - make rpm
  artifacts:
    paths:
    - rpmbuild/RPMS/x86_64/*.rpm
    when: always
    expire_in: 1 week

centos7-rpm-deploy:

  before_script:
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then eval $(ssh-agent -s); fi
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then echo "$SCP_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi

  stage: deploy
  tags: [ "docker-centos7" ]

  only:
    refs:
      - master
    changes:
      - flexisip-http-file-transfer-server.spec

  needs:
    - centos7-rpm

  script:
   - cd rpmbuild/RPMS/x86_64 && rsync -e "ssh -o StrictHostKeyChecking=no" -pr . $DEPLOY_SERVER:$CENTOS7_DEPLOY_DIRECTORY && rsync -e "ssh -o StrictHostKeyChecking=no" -pr . $DEPLOY_SERVER:$CENTOS7_DEPLOY_DIRECTORY_ALPHA
   - ssh $DEPLOY_SERVER "chmod a+r $CENTOS7_DEPLOY_DIRECTORY/*.rpm && createrepo_c --update $CENTOS7_DEPLOY_DIRECTORY/."
   - ssh $DEPLOY_SERVER "chmod a+r $CENTOS7_DEPLOY_DIRECTORY_ALPHA/*.rpm && createrepo_c --update $CENTOS7_DEPLOY_DIRECTORY_ALPHA/."

centos8-rpm:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos:8

  stage: package
  script:
    - make rpm
  artifacts:
    paths:
    - rpmbuild/RPMS/x86_64/*.rpm
    when: always
    expire_in: 1 week

centos8-rpm-deploy:

  before_script:
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then eval $(ssh-agent -s); fi
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then echo "$SCP_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi

  stage: deploy
  tags: [ "docker" ]

  # only:
  #   refs:
  #     - master
  #   changes:
  #     - flexisip-http-file-transfer-server.spec

  needs:
    - centos8-rpm

  script:
   - cd rpmbuild/RPMS/x86_64 && rsync -e "ssh -o StrictHostKeyChecking=no" -pr . $DEPLOY_SERVER:$CENTOS8_DEPLOY_DIRECTORY
   - rsync -e "ssh -o StrictHostKeyChecking=no" -pr . $DEPLOY_SERVER:$CENTOS8_DEPLOY_DIRECTORY_ALPHA
   - ssh $DEPLOY_SERVER "chmod a+r $CENTOS7_DEPLOY_DIRECTORY/*.rpm && createrepo_c --update $CENTOS8_DEPLOY_DIRECTORY/."
   - ssh $DEPLOY_SERVER "chmod a+r $CENTOS8_DEPLOY_DIRECTORY_ALPHA/*.rpm && createrepo_c --update $CENTOS8_DEPLOY_DIRECTORY_ALPHA/."

.debian-deb:

  tags: [ "docker" ]
  stage: package

  script:
    - sudo make deb

  artifacts:
    paths:
    - rpmbuild/DEBS/x86_64/*.deb
    when: always
    expire_in: 1 week

debian10-deb:
  extends: .debian-deb
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian10:20220913_mariadb_as_service

debian11-deb:
  extends: .debian-deb
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:20211108_init

.debian-deb-upload:
  tags: [ "macmini-deploy" ]
  stage: deploy

  only:
    refs:
      - master
    changes:
      - flexisip-http-file-transfer-server.spec

  before_script:
    - TMP_LOCALE=$LC_CTYPE
    - echo $LC_CTYPE

  script:
    - export LC_CTYPE=C
    - id=$(cat /dev/urandom | tr -dc '[:alnum:]' | fold -w 10 | head -n 1) || true
    - tmpdir="$MAKE_REPO_TMP/tmp-$id" || true
    - rsync_dest="$DEPLOY_SERVER:$tmpdir/"
    - echo ">>> Pushing packages into '$rsync_dest'"
    - rsync -rv rpmbuild/DEBS/x86_64/*.deb $rsync_dest
    - ssh $DEPLOY_SERVER "echo \">>>> Making repository with Freight\";  (freight add --conf=$FREIGHT_PATH $tmpdir/*.deb apt/$RELEASE/$BRANCH && freight cache --conf=$FREIGHT_PATH apt/$RELEASE) || exit 1; echo \">>>> Removing '$tmpdir'\"; rm -r $tmpdir"

  after_script:
    - echo $LC_CTYPE
    - echo $TMP_LOCALE
    - export LC_CTYPE=$TMP_LOCALE

debian10-deb-deploy:
  extends: .debian-deb-upload

  variables:
    RELEASE: buster
    BRANCH: stable
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH

  needs:
    - debian10-deb

debian11-deb-deploy:
  extends: .debian-deb-upload

  variables:
    RELEASE: bullseye
    BRANCH: stable
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH

  needs:
    - debian11-deb

ubuntu-18.04-deb:
  extends: .debian-deb
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-ubuntu-18-04-lts-php:2023_01_24_rebuild_image

ubuntu-18.04-deb-deploy:
  extends: .debian-deb-upload

  variables:
    RELEASE: bionic
    FREIGHT_PATH: $UBUNTU_FREIGHT_CONF_PATH

  needs:
    - ubuntu-18.04-deb

stages:
 - package
 - deploy
