centos7-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7-php:$CENTOS_7_IMAGE_VERSION
  script:
    - make rpm-el7

rocky8-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-rocky8-php:$ROCKY_8_IMAGE_VERSION
  script:
    - make rpm

rocky9-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky9-php:$ROCKY_9_IMAGE_VERSION
  script:
    - make rpm-el9

debian11-package:
  extends: .debian-package
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11-php:$DEBIAN_11_IMAGE_VERSION

debian12-package:
  extends: .debian-package
  image: gitlab.linphone.org:4567/bc/public/docker/debian12-php:$DEBIAN_12_IMAGE_VERSION

.debian-package:
  extends: .package
  script:
    - make deb

.package:
  tags: ["docker"]

  stage: package
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 1 day
